language: php
php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer install

matrix:
  fast_finish: true
  include:
    # test the latest stable 3.x release
    - php: 5.6
      env: SYMFONY_VERSION=^3.0
    # test the latest release (including beta releases)
    - php: 7.2
      env: DEPENDENCIES=beta

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/framework-bundle:${SYMFONY_VERSION}" --no-update; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/console:${SYMFONY_VERSION}" --no-update; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/process:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS
